### ISSUE TITLE
Doesn't build with OpenJDK 8

### ISSUE THREAD

**Issue by niclash** [goldmansachs/reladomo#86] opened 2017-07-23 00:54 UTC
On Debian Linux;

    /usr/lib/jvm/java-1.8.0-openjdk-amd64//lib/rt.jar:build/lib/*:/usr/lib/jvm/java-1.8.0-openjdk-amd64//lib/tools.jar
    OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
    Unrecognized VM option 'UseSpinning'
    Error: Could not create the Java Virtual Machine.
    Error: A fatal exception has occurred. Program will exit.

I think it is a bit much to require JDK 1.6 for builds in this day and age...

**Comment by gs-rezaem** [comment] 2017-07-30 21:15
Duplicate of #81 
The BUILD.md file states: Reladomo is currently built with JDK 1.6.
Backward compatibility is one of our core deliverables. We'll eventually move to 1.8, but probably not in the near future.
Building with 1.8 requires changes because the JDK sql interfaces changed. I have a [branch here](https://github.com/gs-rezaem/reladomo/tree/jdk18) that builds with 1.8, but it was just an experiment and I don't intend to keep it up to date.
Binaries are available in maven central, so as a user, there is no reason to build this yourself. If you're building because you intend to contribute, you're better off just downloading 1.6.

**Closed by gs-rezaem** 2017-07-30 21:15 UTC
